# Generated by Django 4.1.4 on 2022-12-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biyografiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oyuncu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oyuncu_adi', models.CharField(max_length=200)),
                ('oyuncu_aciklama', models.TextField()),
                ('resim', models.CharField(max_length=100)),
                ('anasayfa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tarihci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarihci_adi', models.CharField(max_length=200)),
                ('tarihci_aciklama', models.TextField()),
                ('resim', models.CharField(max_length=100)),
                ('anasayfa', models.BooleanField(default=False)),
            ],
        ),
    ]
